### ISSUE TITLE
Bot randomly stops reporting scores on busy nights...

### ISSUE THREAD

**Issue by sprx97** [Spartan97/OldTimeHockey#32]
Need to add some debug statements, but gonna be hard. Maybe create output file.

**Comment by sprx97** [comment]
Seems like the check_scores call is blocking for too long, which causes me to disconnect from Discord and quit... Sounds like the heartbeat is ~60 seconds.

Looks like the 0.16 version of discord.py doesn't support setting the heartbeat_interval variable. 1.0.0a does, but that would involve a large rewrite. For now I just edited the library to use 120 instead of whatever its getting from heartbeat_interval (which I believe is 60).

**Comment by Spartan97** [comment]
Might need to use "yield from" to encompass the check_scores call and related messages. I believe that call is synchronous (blocking) and causing my problem.

**Comment by sprx97** [comment]
Fixed it by making each game a separate blocking call, instead of one blocking call for all the games.
